subprojects{
	apply plugin: "java"

	group = projectGroup
	version = projectVersion

	java{
		sourceCompatibility = sourceCompatibility
	}

	repositories{
		mavenCentral()
	}

	dependencies{
		testImplementation 'org.junit.jupiter:junit-jupiter:5.7.1'
		testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	}

	tasks.named('test', Test){
		useJUnitPlatform()

		testLogging{
			events "passed"
		}
	}
}

project(":base"){
	description = baseDescription

	apply plugin: "java-library"
}

project(":config"){
	description = configDescription

	apply plugin: "java-library"

	dependencies{
		api project(":base")
	}
}
project(":i18n"){
	description = configDescription

	apply plugin: "java-library"

	dependencies{
		api project(":base")
		implementation project(":config")
	}
}