// Inspired from: https://www.pushing-pixels.org/2021/11/30/gradle-copying-all-multi-module-dependencies-to-a-local-folder.html
task flatLibJars(type: Copy){
	group = "Build"
	description = "Copy all library's jars from every subprojects to one folder."
	from{
		subprojects.findAll{ it.plugins.hasPlugin("java-library") }
			.collect{ it.tasks.jar }
	}
	into layout.buildDirectory.dir("libs")
}
task clean(type: Delete) {
	group = "Build"
	description = "Deletes the build directory."
	delete rootProject.buildDir
}

subprojects{
	apply plugin: "java"

	group = projectGroup
	version = projectVersion

	java{
		sourceCompatibility = sourceCompatibility
	}
	tasks.withType(JavaCompile){
		options.compilerArgs.add("-Xlint:all")
		options.compilerArgs.add("-Werror")
		options.deprecation = true
	}

	repositories{
		mavenCentral()
	}

	dependencies{
		testImplementation platform("org.junit:junit-bom:5.10.0")
		testImplementation "org.junit.jupiter:junit-jupiter"
		testRuntimeOnly "org.junit.platform:junit-platform-launcher"
	}

	tasks.named("test", Test){
		useJUnitPlatform()

		testLogging{
			events "passed"
		}
	}
}

project(":base"){
	description = baseDescription

	apply plugin: "java-library"
}

project(":config"){
	description = configDescription

	apply plugin: "java-library"

	dependencies{
		api project(":base")
	}
}
project(":i18n"){
	description = configDescription

	apply plugin: "java-library"

	dependencies{
		api project(":base")
		implementation project(":config")
	}
}
project(":logger"){
	description = configDescription

	apply plugin: "java-library"

	dependencies{
		api project(":base")
		implementation project(":config")
	}
}

project(":app"){
	description = configDescription

	apply plugin: "java-library"

	dependencies{
		api project(":base")
		api project(":config")
		api project(":i18n")
		api project(":logger")
	}
}