projectPrettyName=Java Utils - Project Utils
projectVendor=pimous.dev
projectGroup=dev.pimous

projectVersion=1.0.0

projectMaintainer=contact@pimous.dev
projectCopyright=Copyright © 2026 - Pimous Dev.
projectLicense=LGPL-v3

sourceCompatibility=25
runWorkingDir=tmp

# Base
baseDescription=Base classes and utilities needed by all JUtils modules.

# Config
configDescription=A configuration library.

# I18n
i18nDescription=An internationalization module replacing java resource bundles.

# Logger
loggerDescription=A logging library similar to JUL with different levels and predefined back-end.

# App
appDescription=An application framework.