projectPrettyName=Java Utils - Project Utils
project.group=dev.pimous.pu.jutils
project.url=https://github.com/PimousDev/JUtils
project.version=1.1.0-s.5

project.org.name=Pimous Dev.
project.org.url=https://github.com/PimousDev
project.org.copyright=Copyright © 2026 - Pimous Dev.
project.org.contact=contact@pimous.dev

project.license.name=LGPL-v3
project.license.url=https://www.gnu.org/licenses/lgpl-3.0.txt

# Base
base.description=Base classes and utilities needed by all JUtils modules.

# Config
config.description=A configuration library.

# I18n
i18n.description=An internationalization module replacing java resource bundles.

# Logger
logger.description=A logging library similar to JUL with different levels and \
  predefined back-end.

# App
app.description=An application framework.

# UI
ui.description=A library extending Swing models and components.

# ---
sourceCompatibility=25
runWorkingDir=tmp