plugins{
	id "java"
}

group = projectGroup
version = projectVersion

repositories{
	mavenCentral()

	flatDir{
		dir(rootProject.layout.projectDirectory.dir("lib"))
	}
}
dependencies{
	compileOnly "org.jetbrains:annotations:26.1.0"

	testImplementation platform("org.junit:junit-bom:5.10.0")
	testImplementation "org.junit.jupiter:junit-jupiter"
	testRuntimeOnly "org.junit.platform:junit-platform-launcher"
}

tasks.withType(JavaCompile).configureEach{
	options.compilerArgs.add("-Xlint:all")
	options.compilerArgs.add("-Werror")
	options.deprecation = true
}

tasks.withType(Test).configureEach{
	useJUnitPlatform()
	maxParallelForks = Runtime.runtime.availableProcessors().intdiv(2) ?: 1
}