plugins{
	id "java-library"

	id "jutils"
	id "jutils.jar.libs"
}

description = property("i18n.description")

dependencies{
	api project(":base")
}

publishing{
	publications{
		maven(MavenPublication){
			from components.java

			pom{
				name = "${projectPrettyName} - I18n"
				description = project.description
			}
		}
	}
}