plugins{
	id "java-library"

	id "jutils"
}

description = property("config.description")

dependencies{
	api project(":base")
}

publishing{
	publications{
		maven(MavenPublication){
			from components.java

			pom{
				name = "${projectPrettyName} - Config"
				description = project.description
			}
		}
	}
}