plugins{
	id "java-library"

	id "jutils"
	id "jutils.ftest"
	id "jutils.jar.libs"
}

description = property("base.description")

publishing{
	publications{
		maven(MavenPublication){
			from components.java

			pom{
				name = "${projectPrettyName} - Base"
				description = project.description
			}
		}
	}
}